### ISSUE TITLE
%PLAY_VERSION% should be rendered as latest version for *.*.x

### ISSUE THREAD

**Issue by gmethvin** [playframework/play-doc#20]
For example in https://www.playframework.com/documentation/2.4.x/NewApplication we have:

``` scala
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.4.x")
```

which doesn't really make sense. It should just render as the latest version in 2.4.x series.

**Comment by wsargent** [comment]
See https://github.com/playframework/play-doc/blob/master/src/main/scala/play/doc/PlayDoc.scala#L50 for a starting point

**Comment by dwijnand** [comment]
Nowadays we don't present that info.  We point at starter repos and giter seeds.
