### ISSUE TITLE
Play doc should provide easy linking to Play API

### ISSUE THREAD

**Issue by wsargent** [playframework/play-doc#7]
Given a document which contains text in the format:

```
@[play.api.GlobalSettings]
```

play-doc should generate the Markdown equivalent of the link to scaladoc (or javadoc): 

```
[`play.api.GlobalSettings`](api/scala/index.html#play.api.GlobalSettings)
```

This may be awkward for singleton objects, which have the link ending in $, i.e. api/scala/index.html#play.api.DefaultGlobal$

So perhaps some specification could be used:

```
@[play.api.DefaultGlobal](singleton)
```

Or we could just specify it as the anchor tag directly:

```
@[play.api.DefaultGlobal$]
```

**Comment by dwijnand** [comment]
This should be ported to Paradox, if it's a missing feature.
